# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

api_version = "2023-07"

[[extensions]]
name = "org-number"
type = "ui_extension"
handle = "org-number"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[[extensions.metafields]]
namespace = "adluna"
key = "org_number"

[extensions.capabilities]
api_access = true
network_access = false
block_progress = true


[extensions.settings]

[[extensions.settings.fields]]
key = "required"
type = "boolean"
name = "Required"
description = "Whether the customer should be required to enter this field."

[[extensions.settings.fields]]
key = "validation"
type = "boolean"
name = "Validation"
description = "Whether the org number's formatting will be checked."
